try:
    x = __
    y = __
    print(___) #일부러 에러를 내보자
    print("에러가 발생하지 않았습니다.")
except:
    print("에러가 발생했습니다.")